version: '3.8'

services:

  backend:
    build: ./services/backend
    image: stoiacs/iiasa-backend:1.0.0
    ports:
      - 5001:5001
    volumes:
      - ./services/backend:/app
    environment:
      - DATABASE_URL=postgres://stoia:12345@db:5432/stoia
      - SECRET_KEY=09d25e094faa6ca2556c818166b7a9563b93f7099f6f0f4caa6cf63b88e8d3e7
    command: uvicorn src.main:app --reload --host 0.0.0.0 --port 5001

  frontend:
    build: ./services/frontend
    image: stoiacs/iiasa-frontend:1.0.0
    volumes:
      - './services/frontend:/app'
      - '/app/node_modules'
    ports:
      - 8080:8080

  db:
    image: postgres:15.1
    expose:
      - 5432
    ports:
      - 5433:5432
    environment:
      - POSTGRES_USER=stoia
      - POSTGRES_PASSWORD=12345
      - POSTGRES_DB=stoia
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data:
